### PR TITLE
Update RR hardcore mode sets

### PR DESCRIPTION
**Pull request by May8th1995**
File automatically generated with https://github.com/May8th1995/RRHCjsgen

Updates sets to 3.0.2 as well as fixing minor bugs like U-Turn being spelt wrong and not loading into the calc correctly. Script should be usable for future updates with some minor modifications too.

### CODE REVIEW

**Comment by Karthik99999** [comment]
Hey, thanks for making that script! There's just a couple changes that need to be done.

- `-Gmax` should be changed to `-Mega` for the Gmax mons that became Megas in RR.
- If an IV is 31, it should just not be added as a property (e.g. if a mon has a 0 atk IV and the rest are 31, only `"at":0` should be present). This should drastically cut down the file size.
- A couple pokemon seem to be missing an ability.

Other than that it looks fine.

**Comment by May8th1995** [comment]
All gmaxes should be fixed, IVs should be now shortened, fixed the mega ability bug, also fixed a bug with hidden power not showing the correct type.

Should be ready for rereview.

**Comment by Karthik99999** [comment]
~~ignore my botched rebase~~

ok one last thing, Centiskorch-Sevii-Mega isn't properly accounted for
```diff
elif mon.item == 'ITEM_CENTISKITE':
        if mon.species == 'SPECIES_CENTISKORCH':
            mon.species = 'SPECIES_CENTISKORCH_GIGA'
-       elif mon.species == 'SPECIES_CENTISKORCH':
+       elif mon.species == 'SPECIES_CENTISKORCH_S':
            mon.species = 'SPECIES_CENTISKORCH_S_MEGA'
```
once this gets fixed I should be able to merge it

**Comment by May8th1995** [comment]
Should be all done now.

**Comment by Karthik99999** [comment]
Thank you!

**Pull request merged**
